### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by chadzilla2080**
Removed the last period on line 28 and then added and exclamation point. I merely did this to follow along with the PHP Study Group Video, "Contributing to Open Source Projects".

### CODE REVIEW

**Comment by dstockto** [comment]
Thanks for the pull request. Next step is to find a project and make a non-trivial pull request :)

**Comment by chadzilla2080** [comment]
I'm sorry I only made it through the first 36 mins of the video, I was busy taking notes to my Google Doc drive to capture all steps of the lesson. So are you implying that I find another open source project on GitHub?

**Comment by dstockto** [comment]
I'm saying you've now got a pull request done, but it's good to find a project and make a contribution like adding a feature, fixing a bug, updating documentation, etc that is more significant. You're more than welcome to continue to help with and contribute to kidsquest,  and I hope that you do. The point of the video is that there's a ton of open source projects that need help and we should all be making contributions where we can.

**Comment by chadzilla2080** [comment]
Gottcha, I still have four more videos to watch. I took some serious notes and made my own study guides on Google Docs. I am currently learning a lot on Unix/Linux file system, shells, and commands....lot on my plate. But the videos have been very helpful. Thanks, I will look into Drupal and some other Open Source Projects on here tonight.

**Pull request merged**
